[package]
name = "ttimes"
version = "0.1.0"
authors = ["Michal Skalski <michal@skalski.org>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
prettytable-rs = "^0.8"
clap = "~2.33"
